spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gcp:
      sql:
        instance-connection-name: ${GCP_CONN_NAME}
        database-name: ${DB_NAME}

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.wp.pl
    port: 465
    username: ${SPRING_MAIL_USERNAME}1
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  server:
    port: ${PORT:8080}
